version: "3.8"

services:
  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=app
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=Letusdoit000
    volumes:
      - ./volumes/postgres:/var/lib/postgresql/data
  minio:
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ./volumes/minio:/data
    environment:
      - MINIO_ACCESS_KEY=minioadmin
      - MINIO_SECRET_KEY=minioadmin
    command: server /data --console-address ":9001" -address ":9000"
    healthcheck:
      test:
        [
          "CMD",
          "curl",
          "-f",
          "http://localhost:9001/minio/health/live"
        ]
      interval: 30s
      timeout: 20s
      retries: 3
  pgadmin:
    image: dpage/pgadmin4
    ports:
      - "8081:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=insiinc@outlook.com
      - PGADMIN_DEFAULT_PASSWORD=Letusdoit000
  tusd:
    image: tusproject/tusd
    ports:
      - "8080:8080"
    environment:
      - AWS_REGION=cn-north-1
      - AWS_ACCESS_KEY_ID=minioadmin
      - AWS_SECRET_ACCESS_KEY=minioadmin

    command: -verbose -s3-bucket app -s3-endpoint http://minio:9000
    volumes:
      - ./volumes/tusd:/data
  redis:
    image: redis:latest
    ports:
        - "6379:6379"
    volumes:
        - ./volumes/redis:/data